
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.resource
{
public sealed partial class SettingOptionResource : Luban.BeanBase
{
    public SettingOptionResource(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (SettingType)_buf["type"].AsInt; }
        { if(!_buf["optionSelection"].IsNumber) { throw new SerializationException(); }  OptionSelection = (SettingOptionSelection)_buf["optionSelection"].AsInt; }
        { if(!_buf["optionType"].IsNumber) { throw new SerializationException(); }  OptionType = (SettingOptionType)_buf["optionType"].AsInt; }
    }

    public static SettingOptionResource DeserializeSettingOptionResource(JSONNode _buf)
    {
        return new resource.SettingOptionResource(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly SettingType Type;
    /// <summary>
    /// 标题
    /// </summary>
    public readonly SettingOptionSelection OptionSelection;
    /// <summary>
    /// 选项形式
    /// </summary>
    public readonly SettingOptionType OptionType;
   
    public const int __ID__ = 1320548371;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "optionSelection:" + OptionSelection + ","
        + "optionType:" + OptionType + ","
        + "}";
    }
}

}

