
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 设置类型
    /// </summary>
    public enum SettingType
    {
        /// <summary>
        /// 画面
        /// </summary>
        GRAPHIC = 1,
        /// <summary>
        /// 音效
        /// </summary>
        AUDIO = 2,
        /// <summary>
        /// 控制
        /// </summary>
        CONTROL = 3,
        /// <summary>
        /// 语言
        /// </summary>
        LANGUAGE = 4,
    }

} 

