
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 设置选项内容-显示方式
    /// </summary>
    public enum SettingOptionSelectionDisplay
    {
        /// <summary>
        /// 全屏
        /// </summary>
        EXCLUSIVE_FULLSCREEN = 1,
        /// <summary>
        /// 窗口化全屏
        /// </summary>
        FULLSCREEN_WINDOW = 2,
        /// <summary>
        /// 窗口
        /// </summary>
        WINDOW = 3,
    }

} 

