
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 设置选项内容-语言
    /// </summary>
    public enum SettingOptionLanguage
    {
        /// <summary>
        /// 简体中文
        /// </summary>
        CHINESE_SIMPLE = 1,
        /// <summary>
        /// 繁体中文
        /// </summary>
        CHINESE_TRADITION = 2,
        /// <summary>
        /// 英语
        /// </summary>
        ENGLISH = 3,
    }

} 

