
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 设置选择项
    /// </summary>
    public enum SettingOptionSelection
    {
        /// <summary>
        /// 显示方式
        /// </summary>
        GRAPHIC_DISPLAY_MODE = 1,
        /// <summary>
        /// 分辨率
        /// </summary>
        GRAPHIC_RESOLUTION = 2,
        /// <summary>
        /// 垂直同步
        /// </summary>
        GRAPHIC_VSYNC = 3,
        /// <summary>
        /// 总音量
        /// </summary>
        AUDIO_TOTAL = 4,
        /// <summary>
        /// 音乐音量
        /// </summary>
        AUDIO_MUSIC = 5,
        /// <summary>
        /// 效果音量
        /// </summary>
        AUDIO_EFFECT = 6,
        /// <summary>
        /// 移动-上
        /// </summary>
        KEY_MOVE_UP = 7,
        /// <summary>
        /// 移动-下
        /// </summary>
        KEY_MOVE_DOWN = 8,
        /// <summary>
        /// 移动-左
        /// </summary>
        KEY_MOVE_LEFT = 9,
        /// <summary>
        /// 移动-右
        /// </summary>
        KEY_MOVE_RIGHT = 10,
        /// <summary>
        /// 冲刺
        /// </summary>
        KEY_DASH = 11,
        /// <summary>
        /// 语言
        /// </summary>
        LANGUAGE = 12,
    }

} 

