
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 设置项类型
    /// </summary>
    public enum SettingOptionType
    {
        /// <summary>
        /// 选项切换
        /// </summary>
        SWITCH_OPTIONS = 1,
        /// <summary>
        /// 布尔切换
        /// </summary>
        SWITCH_BOOL = 2,
        /// <summary>
        /// 按键绑定
        /// </summary>
        KEY_BIND = 3,
        /// <summary>
        /// 拖动条
        /// </summary>
        DRAG_BAR = 4,
    }

} 

