
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 设置选项-二象性选项
    /// </summary>
    public enum SettingOptionDualitySelection
    {
        /// <summary>
        /// 关闭
        /// </summary>
        OFF = 0,
        /// <summary>
        /// 开启
        /// </summary>
        ON = 1,
    }

} 

