
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.cfgObj
{
/// <summary>
/// 设置选项表
/// </summary>
public partial class SettingOptionObj
{
    private readonly System.Collections.Generic.Dictionary<int, resource.SettingOptionResource> _dataMap;
    private readonly System.Collections.Generic.List<resource.SettingOptionResource> _dataList;
    
    public SettingOptionObj(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, resource.SettingOptionResource>();
        _dataList = new System.Collections.Generic.List<resource.SettingOptionResource>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            resource.SettingOptionResource _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.resource.SettingOptionResource.DeserializeSettingOptionResource(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, resource.SettingOptionResource> DataMap => _dataMap;
    public System.Collections.Generic.List<resource.SettingOptionResource> DataList => _dataList;

    public resource.SettingOptionResource GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public resource.SettingOptionResource Get(int key) => _dataMap[key];
    public resource.SettingOptionResource this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

